subscription_id: "SUBSCRIPTION_ID_FOR_FIRST_INSTANCE"
resource_group: "RESOURCE_GROUP_NAME_FOR_FIRST_INSTANCE"
workspace_name: "WORKSPACE_NAME_FOR_FIRST_INSTANCE"
instance_name: "GPU_INSTANCE_NAME_FOR_FIRST_INSTANCE"